version: '3.8'
services:

services:
  nextjs:
    container_name: nextjs
    build:
      context: ./
    image: nextjs
    ports:
      - '3000:3000'
    
  postgres:
    image: 'postgres:17-alpine'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: next-lms
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
